-- Fictional local-only records for exercising the public and admin interfaces.
-- Individual names, dates, weights, prices, temperaments, feeding histories,
-- shed cadence, availability, and images are illustrative—not real inventory.

PRAGMA foreign_keys = ON;

INSERT INTO snakes (
  id,
  slug,
  name,
  species,
  description,
  price_in_cents,
  available,
  featured,
  primary_image_key,
  sex,
  hatch_date,
  personality,
  feeding_notes,
  diet,
  shed_frequency,
  temperature,
  humidity,
  weight_grams,
  complementary_genetics,
  status,
  created_at,
  updated_at
) VALUES
  (
    'demo-specimen-juniper',
    'demo-juniper-piebald-ball-python',
    'Juniper',
    'Ball python · Python regius',
    'Fictional demo specimen—not a real animal or an offer for sale. Juniper demonstrates a complete profile with a research-supported recessive Piebald chip, full husbandry notes, a price, and a linked complementary project.',
    45000,
    1,
    1,
    'snakes/demo/ball-python-v2.webp',
    'male',
    '2024-05-18',
    'Fictional profile: settled and unhurried during short handling sessions, with a strong preference for covered resting spaces.',
    'Fictional record: consistently accepts appropriately sized frozen-thawed whole prey; response and body condition would be reviewed before each offering.',
    'Appropriately sized frozen-thawed whole prey',
    'Fictional cadence: approximately every 5–7 weeks.',
    'Demo husbandry note: provide and measure a species-appropriate warm-to-cool gradient rather than one uniform enclosure temperature.',
    'Demo husbandry note: maintain a species-appropriate baseline with access to more humidity around shedding; verify with calibrated instruments.',
    1380,
    'demo-moss-piebald-ball-python',
    'available',
    unixepoch() - 60,
    unixepoch() - 60
  ),
  (
    'demo-specimen-saffron',
    'demo-saffron-amel-corn',
    'Saffron',
    'Corn snake · Pantherophis guttatus',
    'Fictional demo specimen—not a real animal or an offer for sale. Saffron shows a bright colubrid-style listing, a research-supported recessive Amelanistic chip, complete measurements, and a complementary corn snake project.',
    32500,
    1,
    1,
    'snakes/demo/corn-snake-v2.webp',
    'female',
    '2023-08-09',
    'Fictional profile: alert and exploratory, then steady once supported with two hands.',
    'Fictional record: reliably takes appropriately sized frozen-thawed whole prey; feeding response and weight would be logged.',
    'Appropriately sized frozen-thawed whole prey',
    'Fictional cadence: approximately every 4–6 weeks.',
    'Demo husbandry note: provide a measured thermal gradient with secure hides at both warmer and cooler positions.',
    'Demo husbandry note: use a moderate species-appropriate baseline and a humid retreat when needed for shedding.',
    620,
    'demo-lumen-amel-corn',
    'available',
    unixepoch() - 120,
    unixepoch() - 120
  ),
  (
    'demo-specimen-poppy',
    'demo-poppy-western-hognose',
    'Poppy',
    'Western hognose · Heterodon nasicus',
    'Fictional demo specimen—not a real animal or an offer for sale. Poppy demonstrates the reserved state, compact-species presentation, fossorial context, and a defensive-behaviour caveat without promising temperament.',
    60000,
    0,
    1,
    'snakes/demo/western-hognose-v2.webp',
    'female',
    '2024-07-02',
    'Fictional profile: active underground and capable of normal hognose bluffing when startled. Western hognose snakes are rear-fanged; handling and placement require an informed keeper.',
    'Fictional record: accepts appropriately sized frozen-thawed whole prey. Intake, body condition, and unusual refusals would be recorded rather than treated as a fixed schedule.',
    'Appropriately sized frozen-thawed whole prey',
    'Fictional cadence: approximately every 4–6 weeks.',
    'Demo husbandry note: provide a measured warm-to-cool gradient and deep, safe substrate that supports fossorial behaviour.',
    'Demo husbandry note: avoid a uniformly damp enclosure; provide clean water and a localized humid retreat when appropriate.',
    230,
    NULL,
    'reserved',
    unixepoch() - 180,
    unixepoch() - 180
  ),
  (
    'demo-specimen-cedar',
    'demo-cedar-kenyan-sand-boa',
    'Cedar',
    'Kenyan sand boa · Eryx colubrinus',
    'Fictional demo specimen—not a real animal or an offer for sale. Cedar demonstrates the placed state, a compact fossorial profile, complete care sections, and an illustrative R2-backed image.',
    27500,
    0,
    1,
    'snakes/demo/kenyan-sand-boa-v2.webp',
    'male',
    '2022-11-14',
    'Fictional profile: spends most daylight hours buried and surfaces predictably around routine enclosure activity.',
    'Fictional record: accepts appropriately sized frozen-thawed whole prey; feeding and weight trends would be tracked together.',
    'Appropriately sized frozen-thawed whole prey',
    'Fictional cadence: approximately every 6–8 weeks.',
    'Demo husbandry note: provide a measured thermal gradient across substrate suitable for burrowing.',
    'Demo husbandry note: maintain a comparatively dry, well-ventilated setup with clean water and targeted shedding support.',
    410,
    NULL,
    'sold',
    unixepoch() - 240,
    unixepoch() - 240
  ),
  (
    'demo-specimen-mica',
    'demo-mica-california-kingsnake',
    'Mica',
    'California kingsnake · Lampropeltis californiae',
    'Fictional demo specimen—not a real animal or an offer for sale. Mica intentionally has no price and no recorded genetic chips so the public and admin fallbacks remain visible.',
    0,
    1,
    0,
    NULL,
    NULL,
    '2023-06-21',
    'Fictional profile: food-motivated and active; handling would be kept separate from feeding cues and supported along the body.',
    'Fictional record: takes appropriately sized frozen-thawed whole prey. Kingsnakes are ophiophagous, so this demo assumes secure individual housing.',
    'Appropriately sized frozen-thawed whole prey',
    NULL,
    'Demo husbandry note: provide a measured warm-to-cool gradient with secure hides and room for active exploration.',
    'Demo husbandry note: maintain a species-appropriate moderate baseline, clean water, and shedding support as needed.',
    760,
    NULL,
    'available',
    unixepoch() - 300,
    unixepoch() - 300
  ),
  (
    'demo-specimen-ember',
    'demo-ember-boa-imperator',
    'Ember',
    'Boa imperator · Boa imperator',
    'Fictional demo specimen—not a real animal or an offer for sale. Ember demonstrates a larger-bodied species, the placed state, an intentionally unpriced historical record, and the need to plan for substantial adult space.',
    0,
    0,
    0,
    NULL,
    'female',
    '2021-04-30',
    'Fictional profile: composed when fully supported. This listing avoids describing a large constrictor as universally docile.',
    'Fictional record: accepts appropriately sized frozen-thawed whole prey. Portion size, body condition, and growth would be reviewed carefully to avoid overfeeding.',
    'Appropriately sized frozen-thawed whole prey',
    'Fictional cadence: approximately every 7–10 weeks.',
    'Demo husbandry note: provide a carefully measured thermal gradient and an enclosure planned around adult body size, strength, and climbing opportunities.',
    'Demo husbandry note: maintain a species-appropriate moderate-to-humid range with ventilation and dry surface options.',
    5200,
    NULL,
    'sold',
    unixepoch() - 360,
    unixepoch() - 360
  ),
  (
    'demo-specimen-moss',
    'demo-moss-piebald-ball-python',
    'Moss',
    'Ball python · Python regius',
    'Fictional demo specimen—not a real animal or an offer for sale. Moss demonstrates a second reserved project, a different price and weight, linked complementary genetics, and a research-supported recessive Piebald chip.',
    70000,
    0,
    0,
    'snakes/demo/ball-python-v2.webp',
    'male',
    '2024-09-11',
    'Fictional profile: cautious at first contact and more settled after choosing a supported resting position.',
    'Fictional record: currently accepts appropriately sized frozen-thawed whole prey; refusals would be documented alongside weight and seasonal context.',
    'Appropriately sized frozen-thawed whole prey',
    'Fictional cadence: approximately every 5–7 weeks.',
    'Demo husbandry note: provide and measure a species-appropriate warm-to-cool gradient with snug hides.',
    'Demo husbandry note: maintain a species-appropriate baseline and localized shedding support without leaving all substrate wet.',
    920,
    'demo-juniper-piebald-ball-python',
    'reserved',
    unixepoch() - 420,
    unixepoch() - 420
  ),
  (
    'demo-specimen-lumen',
    'demo-lumen-amel-corn',
    'Lumen',
    'Corn snake · Pantherophis guttatus',
    'Fictional demo specimen—not a real animal or an offer for sale. Lumen deliberately has no image key so the neutral placeholder, image-alt fallback, and complementary-link treatment are all exercised.',
    35000,
    1,
    0,
    NULL,
    'male',
    '2024-03-16',
    'Fictional profile: inquisitive and quick-moving, with handling kept low and fully supported.',
    'Fictional record: accepts appropriately sized frozen-thawed whole prey; each meal and weight check would be recorded.',
    'Appropriately sized frozen-thawed whole prey',
    'Fictional cadence: approximately every 4–6 weeks.',
    'Demo husbandry note: provide a measured thermal gradient, secure hides, climbing structure, and escape-resistant housing.',
    'Demo husbandry note: maintain a moderate species-appropriate baseline and provide focused shedding support when needed.',
    480,
    'demo-saffron-amel-corn',
    'available',
    unixepoch() - 480,
    unixepoch() - 480
  )
ON CONFLICT(id) DO UPDATE SET
  slug = excluded.slug,
  name = excluded.name,
  species = excluded.species,
  description = excluded.description,
  price_in_cents = excluded.price_in_cents,
  available = excluded.available,
  featured = excluded.featured,
  primary_image_key = excluded.primary_image_key,
  sex = excluded.sex,
  hatch_date = excluded.hatch_date,
  personality = excluded.personality,
  feeding_notes = excluded.feeding_notes,
  diet = excluded.diet,
  shed_frequency = excluded.shed_frequency,
  temperature = excluded.temperature,
  humidity = excluded.humidity,
  weight_grams = excluded.weight_grams,
  complementary_genetics = excluded.complementary_genetics,
  status = excluded.status,
  created_at = excluded.created_at,
  updated_at = excluded.updated_at;

DELETE FROM trait_chips
WHERE snake_id LIKE 'demo-specimen-%';

INSERT INTO trait_chips (id, snake_id, label, type) VALUES
  ('demo-trait-juniper-pied', 'demo-specimen-juniper', 'Piebald', 'recessive'),
  ('demo-trait-saffron-amel', 'demo-specimen-saffron', 'Amelanistic', 'recessive'),
  ('demo-trait-moss-pied', 'demo-specimen-moss', 'Piebald', 'recessive'),
  ('demo-trait-lumen-amel', 'demo-specimen-lumen', 'Amelanistic', 'recessive');

INSERT INTO inquiries (
  id,
  snake_id,
  name,
  email,
  message,
  created_at
) VALUES
  (
    'demo-inquiry-juniper',
    'demo-specimen-juniper',
    'Demo Customer',
    'demo.customer@example.com',
    '[Demo inquiry] Could you share the fictional feeding log and explain how the two listed genetics are represented in this sample profile?',
    unixepoch() - 900
  ),
  (
    'demo-inquiry-mica',
    'demo-specimen-mica',
    'Sample Keeper',
    'sample.keeper@example.com',
    '[Demo inquiry] This message exists only to show the admin inbox, specimen link, customer email treatment, and multiline message layout.',
    unixepoch() - 1800
  )
ON CONFLICT(id) DO UPDATE SET
  snake_id = excluded.snake_id,
  name = excluded.name,
  email = excluded.email,
  message = excluded.message,
  created_at = excluded.created_at;
